# Generated by Django 4.2.1 on 2023-05-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-pub_date']},
        ),
    ]
